ski-station-api:
  build: .
  restart: always
  ports:
    - 8089:8089
  depends_on:
    - mysqldb

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: yes